version: '3.8'

services:
  rabbitmq:
    image: cloudsolutionrepository001.azurecr.io/rabbitmq:1.0.1
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # Opcional: Arquivo de configuração personalizado
      # - ./enabled_plugins:/etc/rabbitmq/enabled_plugins  # Opcional: Arquivo de plugins personalizados
    environment:
      - RABBITMQ_DEFAULT_USER=guest  
      - RABBITMQ_DEFAULT_PASS=guest 

volumes:
  rabbitmq_data:
