version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # Opcional: Arquivo de configuração personalizado
      # - ./enabled_plugins:/etc/rabbitmq/enabled_plugins  # Opcional: Arquivo de plugins personalizados
    environment:
      - RABBITMQ_DEFAULT_USER=dxt743994  
      - RABBITMQ_DEFAULT_PASS=Hts74398#@%  

volumes:
  rabbitmq_data:
